"""them tongsoghe o bang chuyen bay

Revision ID: 39129501e946
Revises: 
Create Date: 2025-03-18 00:02:07.965258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39129501e946'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chuyen_bay', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tong_so_ghe', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chuyen_bay', schema=None) as batch_op:
        batch_op.drop_column('tong_so_ghe')

    # ### end Alembic commands ###
