"""modify phieudat

Revision ID: 3b9fd47e848a
Revises: 39129501e946
Create Date: 2025-03-18 15:24:39.639148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b9fd47e848a'
down_revision = '39129501e946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phieu_dat_cho', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vi_tri', sa.String(length=20), nullable=True))

        

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phieu_dat_cho', schema=None) as batch_op:

        
        batch_op.drop_column('vi_tri')
    
    # ### end Alembic commands ###
