"""them ma nhan vien o bang hoa don

Revision ID: 4fd3d3c3cd78
Revises: 44fabf92fb5a
Create Date: 2025-03-20 12:12:47.180220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fd3d3c3cd78'
down_revision = '44fabf92fb5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hoa_don', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Ma_nhan_vien', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_hoadon_manv', 'nhan_vien', ['Ma_nhan_vien'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hoa_don', schema=None) as batch_op:
        batch_op.drop_constraint('fk_hoadon_manv', type_='foreignkey')
        batch_op.drop_column('Ma_nhan_vien')

    # ### end Alembic commands ###
