"""Sua bang doanh thu

Revision ID: 8af311092157
Revises: 3b9fd47e848a
Create Date: 2025-03-20 12:08:16.380659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8af311092157'
down_revision = '3b9fd47e848a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doanh_thu')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doanh_thu',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('Tong_doanh_thu', sa.FLOAT(), nullable=True),
    sa.Column('ThoiGian', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
